# Generated by Django 5.2.7 on 2025-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pwd_changed',
            field=models.BooleanField(default=False),
        ),
    ]
