# Generated by Django 5.2.7 on 2025-10-04 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_userprofile_is_pwd_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
