# Generated by Django 5.2.7 on 2025-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_userprofile_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('ADMIN', 'ADMIN')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('Not.Binary', 'Not.Binary')], max_length=50, null=True),
        ),
    ]
